package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.21 DO NOT EDIT.

import (
	"context"

	"github.com/go-graphql/auth"
	"github.com/go-graphql/logger"
	"github.com/go-graphql/models"
	"github.com/go-graphql/utils"
	"github.com/sirupsen/logrus"
	"github.com/vektah/gqlparser/gqlerror"
)

// Pokemons is the resolver for the pokemons field.
func (r *queryResolver) Pokemons(ctx context.Context, limit *int, offset *int) ([]*models.Pokemon, error) {
	user, err := auth.ForContext(ctx)
	if err != nil {
		logger.Log.WithFields(logrus.Fields{
			"error": err.Error(),
		}).Error("User Authorization")
		return nil, gqlerror.Errorf(err.Error())
	}

	logger.Log.WithFields(logrus.Fields{
		"user_id":  user.UserID,
		"is_admin": user.IsAdmin,
	}).Info("Pokemons queryResolver")

	res, err := r.PokemonService.FetchAll(ctx, utils.GetSafeInt(limit), utils.GetSafeInt(offset))
	if err != nil {
		return nil, gqlerror.Errorf(err.Error())
	}

	return res, nil
}
