// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import models "github.com/go-graphql/models"

// TypeServiceInterface is an autogenerated mock type for the TypeServiceInterface type
type TypeServiceInterface struct {
	mock.Mock
}

// FetchAll provides a mock function with given fields: ctx, pokemonID
func (_m *TypeServiceInterface) FetchAll(ctx context.Context, pokemonID int) ([]*models.Type, error) {
	ret := _m.Called(ctx, pokemonID)

	var r0 []*models.Type
	if rf, ok := ret.Get(0).(func(context.Context, int) []*models.Type); ok {
		r0 = rf(ctx, pokemonID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Type)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, pokemonID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchOne provides a mock function with given fields: ctx, typeID
func (_m *TypeServiceInterface) FetchOne(ctx context.Context, typeID int) ([]*models.Type, error) {
	ret := _m.Called(ctx, typeID)

	var r0 []*models.Type
	if rf, ok := ret.Get(0).(func(context.Context, int) []*models.Type); ok {
		r0 = rf(ctx, typeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Type)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, typeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
